PruebaTecnicaFrontend/Models/ApiResponse.cs
namespace PruebaTecnicaFrontend.Models
{
    public class ApiResponse
    {
        public string Status { get; set; }
        public string Message { get; set; }
    }
}

PruebaTecnicaFrontend/Models/ErrorViewModel.cs
namespace PruebaTecnicaFrontend.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PruebaTecnicaFrontend/Models/HomeModel.cs
namespace PruebaTecnicaFrontend.Models
{
    public class HomeModel
    {
        public string? BookTitle { get; set; }
        public decimal? BookYear { get; set; }
        public string? BookGenre { get; set; }
        public decimal? BookNumberOfPages { get; set; }
        public string? AuthorFullName { get; set; }
    }
}

PruebaTecnicaFrontend/Models/NumeroModel.cs
namespace PruebaTecnicaFrontend.Models
{
    public class NumeroModel
    {
        public int Numero { get; set; }
    }
}

PruebaTecnicaFrontend/Models/RegisterAuthor.cs
namespace PruebaTecnicaFrontend.Models
{
    public class RegisterAuthor
    {
        public string? FullName { get; set; } = null!;
        public string? DateOfBirth { get; set; }
        public string? CityOfOrigin { get; set; }
        public string? Email { get; set; }
    }
}

PruebaTecnicaFrontend/Models/ResponseModel.cs
namespace PruebaTecnicaFrontend.Models
{
    public class ResponseModel
    {
        public decimal? BookId { get; set; }
        public string? BookTitle { get; set; } = null!;
        public decimal? BookYear { get; set; }
        public string? BookGenre { get; set; }
        public decimal? BookNumberOfPages { get; set; }
        public decimal? AuthorId { get; set; }
        public string? AuthorFullName { get; set; } = null!;
        public string? AuthorDateOfBirth { get; set; }
        public string? AuthorCityOfOrigin { get; set; }
        public string? AuthorEmail { get; set; }
    }
}

PruebaTecnicaFrontend/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PruebaTecnicaFrontend.Models;
using System.Net.Http;
using System.Text;

namespace PruebaTecnicaFrontend.Controllers
{
    public class AuthorController : Controller
    {
        private readonly HttpClient _httpClient;

        public AuthorController(HttpClient httpClient)
        {
            _httpClient = httpClient;
            _httpClient.BaseAddress = new Uri("https://localhost:7130");
        }

        #region RegistrarAutor
        public IActionResult RegisterAutor()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> RegisterAutor(RegisterAuthor registerAuthor)
        {
            string jsonBody = JsonConvert.SerializeObject(registerAuthor);
            var content = new StringContent(jsonBody, Encoding.UTF8, "application/json");

            HttpResponseMessage response = await _httpClient.PostAsync("/Authors/RegisterAuthor", content);
            var responseBody = await response.Content.ReadAsStringAsync();
            var apiResponse = JsonConvert.DeserializeObject<ApiResponse>(responseBody);

            if (apiResponse!.Status == "Ok")
            {
                // La llamada a la API fue exitosa
                TempData["SuccessMessage"] = apiResponse.Message;
            }
            else
            {
                // La llamada a la API falló
                TempData["ErrorMessage"] = apiResponse.Message;
            }
            return View();

        }
        #endregion
    }
}

PruebaTecnicaFrontend/Controllers/BooksController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PruebaTecnicaFrontend.Models;
using System.Text;

namespace PruebaTecnicaFrontend.Controllers
{
    public class BooksController : Controller
    {
        private readonly HttpClient _httpClient;

        public BooksController(HttpClient httpClient)
        {
            _httpClient = httpClient;
            _httpClient.BaseAddress = new Uri("https://localhost:7130");
        }

        [HttpGet]
        public IActionResult Index()
        {
            var books = new List<HomeModel>();
            HttpResponseMessage response = _httpClient.GetAsync("/Books/GetAllBooks").Result;
            if (response.IsSuccessStatusCode)
            {
                var content = response.Content.ReadAsStringAsync().Result;
                List<ResponseModel> json = JsonConvert.DeserializeObject<List<ResponseModel>>(content)!;

                foreach (var item in json)
                {
                    books.Add(new HomeModel
                    {
                        AuthorFullName = item.AuthorFullName,
                        BookGenre = item.BookGenre,
                        BookNumberOfPages = item.BookNumberOfPages,
                        BookTitle = item.BookTitle,
                        BookYear = item.BookYear
                    });
                }
            }
            return View(books);
        }

        #region RegistrarLibro
        public IActionResult RegisterBook()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> RegisterBook(HomeModel createBook)
        {
            string jsonBody = JsonConvert.SerializeObject(createBook);
            var content = new StringContent(jsonBody, Encoding.UTF8, "application/json");

            HttpResponseMessage response = await _httpClient.PostAsync("/Books/RegisterBook", content);
            var responseBody = await response.Content.ReadAsStringAsync();
            var apiResponse = JsonConvert.DeserializeObject<ApiResponse>(responseBody);
            TempData.Clear();
            if (apiResponse!.Status == "Ok")
            {
                TempData["SuccessMessage"] = apiResponse.Message;
            }
            else
            {
                TempData["ErrorMessage"] = apiResponse.Message;
            }
            return View();

        }
        #endregion
    }
}

PruebaTecnicaFrontend/Controllers/InventoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PruebaTecnicaFrontend.Models;
using System.Text;

namespace PruebaTecnicaFrontend.Controllers
{
    public class InventoryController : Controller
    {
        private readonly HttpClient _httpClient;

        public InventoryController(HttpClient httpClient)
        {
            _httpClient = httpClient;
            _httpClient.BaseAddress = new Uri("https://localhost:7130");
        }

        #region UpdateNumberOfRecords
        public IActionResult UpdateNumberOfRecords()
        {
            var numero = new NumeroModel();
            HttpResponseMessage response = _httpClient.GetAsync("/Inventory/GetNumberOfRecords").Result;
            if (response.IsSuccessStatusCode)
            {
                var content = response.Content.ReadAsStringAsync().Result;
                numero.Numero = Convert.ToInt32(content);
            }
            return View(numero);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateNumberOfRecords(NumeroModel records)
        {
            var numero = new NumeroModel();
            var content = new StringContent(records.Numero.ToString(), Encoding.UTF8, "application/json");
            HttpResponseMessage response = await _httpClient.PostAsync("/Inventory/UpdateNumberOfRecords", content);
            var responseBody = await response.Content.ReadAsStringAsync();
            bool apiResponse = bool.Parse(responseBody);
            TempData.Clear();

            if (apiResponse)
            {
                numero.Numero = records.Numero;
                TempData["SuccessMessage"] = "Cantidad máxima de registros actualizada.";
            }
            else
            {
                TempData["ErrorMessage"] = "Ocurrió un error.";
            }
            return View(numero);
        }
        #endregion
    }
}

PruebaTecnicaFrontend/Views/Author/RegisterAutor.cshtml
@model IEnumerable<PruebaTecnicaFrontend.Models.RegisterAuthor>

@{
    ViewData["Title"] = "RegisterAutor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (!string.IsNullOrEmpty(TempData["SuccessMessage"] as string))
{
    <div class="alert alert-success" role="alert">
        @TempData["SuccessMessage"]
    </div>
}

@if (!string.IsNullOrEmpty(TempData["ErrorMessage"] as string))
{
    <div class="alert alert-danger" role="alert">
        @TempData["ErrorMessage"]
    </div>
}
<div class="container-fluid" style="max-width: 50rem; padding-top: 20px;">
    <div class="card">
        <div class="card-header">
            <h3>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                </svg>  Registrar Autor
            </h3>
        </div>
        <div class="card-body">
            <form action="#" method="post" accept-charset="utf-8">
                <div class="row g-2">
                    <div class="col-md">
                        <label for="floatingSelectGrid" class="form-label"><b>Nombre completo:</b></label>
                        <input type="text" required class="form-control" maxlength="100" name="FullName" aria-describedby="FullName">
                    </div>
                    <div class="col-md">
                        <label for="floatingSelectGrid" class="form-label"><b>Fecha de nacimiento:</b></label>
                        <input id="datepicker" required class="form-control" name="DateOfBirth" aria-describedby="DateOfBirth" />
                    </div>
                </div>
                <br />
                <div class="row g-2">
                    <div class="col-md">
                        <div class="col-md">
                            <label for="floatingSelectGrid" class="form-label"><b>Ciudad de procedencia:</b></label>
                            <input type="text" required class="form-control" maxlength="100" name="CityOfOrigin" aria-describedby="CityOfOrigin">
                        </div>
                    </div>
                    <div class="col-md">
                        <div class="col-md">
                            <label for="floatingSelectGrid" class="form-label"><b>Correo electrónico:</b></label>
                            <input type="text" required class="form-control" maxlength="100" name="Email" aria-describedby="Email">
                        </div>
                    </div>
                </div>
                <br />
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <button class="btn btn-success" type="submit">Registrar Autor</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#datepicker").kendoDatePicker();
    });
</script>
<style>
    body {
        margin: 0;
        padding: 0;
        font-family: montserrat;
        background: url(https://images5.alphacoders.com/837/837878.jpg)no-repeat center top;
        background-size: cover;
        font-family: sans-serif;
        height: 100vh;
        backdrop-filter: blur(5px);
    }
</style>

PruebaTecnicaFrontend/Views/Books/Index.cshtml
@*@model IEnumerable<PruebaTecnicaFrontend.Models.HomeModel>
@{
    ViewData["Title"] = "Index";
}

<div class="text-center">
    <h1 class="display-4"><b>Libros</b></h1>
    <hr />
    <div>
        <table class="table table-striped table-hover table-secondary">
            <thead class="table-dark">
                <tr>
                    <th scope="col">Título</th>
                    <th scope="col">Año</th>
                    <th scope="col">Género</th>
                    <th scope="col">Número de páginas</th>
                    <th scope="col">Autor</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@item.BookTitle</th>
                            <td scope="row">@item.BookYear</td>
                            <td scope="row">@item.BookGenre</td>
                            <td scope="row">@item.BookNumberOfPages</td>
                            <td scope="row">@item.AuthorFullName</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel"><b>Eliminar Producto</b></h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="#" method="post" accept-charset="utf-8">
                    <div name="IdProducto" class="modal-body">
                        Desea eliminar el producto id #<label id="idProducto"></label>?
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<style>
    body {
        margin: 0;
        padding: 0;
        font-family: sans-serif;
        background: url(https://static.vecteezy.com/system/resources/previews/004/720/395/original/interior-design-of-school-library-free-vector.jpg)no-repeat center top;
        background-size: cover;
        height: 100vh;
        backdrop-filter: blur(4px);
    }

    .href {
        margin-right: 5px;
    }
</style>*@
@model IEnumerable<PruebaTecnicaFrontend.Models.HomeModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="grid"></div>

<script>
    $(document).ready(function () {
        // Obtener los datos del modelo pasados desde el controlador
        var jsonData = @Html.Raw(Json.Serialize(Model));

        // Crear una instancia de KendoGrid con los datos del modelo
        var grid = $("#grid").kendoGrid({
            dataSource: {
                data: jsonData,
                schema: {
                    model: {
                        fields: {
                            BookTitle: { type: "string" },
                            BookYear: { type: "number" },
                            BookGenre: { type: "string" },
                            BookNumberOfPages: { type: "number" },
                            AuthorFullName: { type: "string" }
                        }
                    }
                }
            },
            columns: [
                { field: "bookTitle", title: "Título" },
                { field: "bookYear", title: "Año" },
                { field: "bookGenre", title: "Género" },
                { field: "bookNumberOfPages", title: "Número de páginas" },
                { field: "authorFullName", title: "Autor" }
            ],
            editable: "inline",
            filterable: true, // Habilitar filtrado
            toolbar: "<h3>Libros</h3>" // Agregar título en la parte superior


        }).data("kendoGrid");

        // Agregar el evento de cambio de filtro
        grid.bind("filterMenuInit", function (e) {
            var filterMultiCheck = e.container.find("[data-role=multiselect]");
            filterMultiCheck.kendoMultiSelect({
                autoClose: false, // Mantener abierto el menú de selección múltiple
                placeholder: "Seleccione...",
                dataSource: {
                    data: grid.dataSource.data(), // Usar los datos actuales para la lista de selección
                    schema: {
                        model: {
                            fields: {
                                // Configurar los campos según las columnas de la KendoGrid
                                BookTitle: { type: "string" },
                                BookYear: { type: "number" },
                                BookGenre: { type: "string" },
                                BookNumberOfPages: { type: "number" },
                                AuthorFullName: { type: "string" }
                            }
                        }
                    }
                },
                dataValueField: "valueField", // Ajustar al campo de la columna correspondiente
                dataTextField: "textField" // Ajustar al campo de la columna correspondiente
            });
        });
    });
</script>
<style>
    body {
        margin: 0;
        padding: 0;
        font-family: sans-serif;
        background: url(https://images5.alphacoders.com/837/837878.jpg)no-repeat center top;
        background-size: cover;
        height: 100vh;
        backdrop-filter: blur(5px);
    }

    .href {
        margin-right: 5px;
    }
</style>

PruebaTecnicaFrontend/Views/Books/RegisterBook.cshtml
@model IEnumerable<PruebaTecnicaFrontend.Models.HomeModel>
@{
    ViewData["Title"] = "RegisterBook";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (!string.IsNullOrEmpty(TempData["SuccessMessage"] as string))
{
    <div class="alert alert-success" role="alert">
        @TempData["SuccessMessage"]
    </div>
}

@if (!string.IsNullOrEmpty(TempData["ErrorMessage"] as string))
{
    <div class="alert alert-danger" role="alert">
        @TempData["ErrorMessage"]
    </div>
}
<div class="container-fluid" style="max-width: 50rem; padding-top: 20px;">
    <div class="card">
        <div class="card-header">
            <h3>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                </svg>  Registrar libro
            </h3>
        </div>
        <div class="card-body">
            <form action="#" method="post" accept-charset="utf-8">
                <div class="row g-2">
                    <div class="col-md">
                        <label for="floatingSelectGrid" class="form-label"><b>Titulo:</b></label>
                        <input type="text" required class="form-control" maxlength="100" name="BookTitle" aria-describedby="BookTitle">
                    </div>
                    <div class="col-md">
                        <label for="floatingSelectGrid" class="form-label"><b>Año:</b></label>
                        <input type="number" required class="form-control" maxlength="10" name="BookYear" aria-describedby="BookYear">
                    </div>
                </div>
                <br />
                <div class="row g-2">
                    <div class="col-md">
                        <div class="col-md">
                            <label for="floatingSelectGrid" class="form-label"><b>Género:</b></label>
                            <input type="text" required class="form-control" maxlength="100" name="BookGenre" aria-describedby="BookGenre">
                        </div>
                    </div>
                    <div class="col-md">
                        <div class="col-md">
                            <label for="floatingSelectGrid" class="form-label"><b>Número de páginas:</b></label>
                            <input type="number" required  class="form-control" maxlength="10" name="BookNumberOfPages" aria-describedby="BookNumberOfPages">
                        </div>
                    </div>
                </div>
                <br />
                <div class="mb-3">
                    <label for="floatingSelectGrid" class="form-label"><b>Autor:</b></label>
                    <input type="text" required class="form-control" maxlength="100" name="AuthorFullName" aria-describedby="AuthorFullName">
                </div>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <button class="btn btn-success" type="submit">Registrar Libro</button>
                </div>
            </form>
        </div>
    </div>
</div>
<style>
    body {
        margin: 0;
        padding: 0;
        font-family: montserrat;
        background: url(https://images5.alphacoders.com/837/837878.jpg)no-repeat center top;
        background-size: cover;
        font-family: sans-serif;
        height: 100vh;
        backdrop-filter: blur(5px);
    }
</style>

PruebaTecnicaFrontend/Views/Inventory/UpdateNumberOfRecords.cshtml
@model PruebaTecnicaFrontend.Models.NumeroModel
@{
    ViewData["Title"] = "UpdateNumberOfRecords";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (!string.IsNullOrEmpty(TempData["SuccessMessage"] as string))
{
    <div class="alert alert-success" role="alert">
        @TempData["SuccessMessage"]
    </div>
}

@if (!string.IsNullOrEmpty(TempData["ErrorMessage"] as string))
{
    <div class="alert alert-danger" role="alert">
        @TempData["ErrorMessage"]
    </div>
}
<div class="container-fluid" style="max-width: 50rem; padding-top: 20px;">
    <div class="card">
        <div class="card-header">
            <h3>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                </svg>  Máximo permitido
            </h3>
        </div>
        <div class="card-body">
            <form action="#" method="post" accept-charset="utf-8">
                <div class="mb-3">
                    <label for="floatingSelectGrid" class="form-label"><b>Cantidad máxima permitida:</b></label>
                    <input type="text" required class="form-control" maxlength="100" value="@Model.Numero" name="Numero" aria-describedby="Numero">
                </div>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <button class="btn btn-success" type="submit">Actualizar máximo permitido</button>
                </div>
            </form>
        </div>
    </div>
</div>
<style>
    body {
        margin: 0;
        padding: 0;
        font-family: montserrat;
        background: url(https://images5.alphacoders.com/837/837878.jpg)no-repeat center top;
        background-size: cover;
        font-family: sans-serif;
        height: 100vh;
        backdrop-filter: blur(5px);
    }
</style>

PruebaTecnicaFrontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PruebaTecnicaFrontend</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PruebaTecnicaFrontend.styles.css" asp-append-version="true" />
    @*Kendo Library*@
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2021.2.616/styles/kendo.common.min.css">
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2021.2.616/styles/kendo.default.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> <!-- Asegúrate de que jQuery se cargue primero -->
    <script src="https://kendo.cdn.telerik.com/2021.2.616/js/kendo.all.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-Secondary bg-white border-bottom box-shadow mb-3" style="background-color: #333; color: white;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Books" asp-action="Index">PruebaTecnicaFrontend</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index"><span class="k-icon k-i-home"></span> Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="RegisterBook"><span class="k-icon k-i-plus"></span> Registrar Libro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="RegisterAutor"><span class="k-icon k-i-plus"></span> Registrar Autor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="UpdateNumberOfRecords"><span class="k-icon k-i-pencil"></span> Máximo Permitido</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
<style>
    /* Estilos en línea para las opciones de navegación */
    .navbar-nav .nav-item .nav-link {
        color: black !important;
    }
    a{
        color: black;
    }
    a:hover{
        color: gray !important;
    }
    /* Estilos en línea para el efecto de "hover" */
    .navbar-nav .nav-item .nav-link:hover {
        color: gray !important; /* Cambia el color en "hover" a gris */
    }

</style>
</html>